apiVersion: apps/v1
kind: Deployment
metadata:
  name: bff
spec:
  replicas: 3
  selector:
    matchLabels:
      app: bff
  template:
    metadata:
      labels:
        app: bff
    spec:
      containers:
      - name: my-container
        image: benjaminucn/devops-taller-bff
        ports:
        - containerPort: 3000
